### ISSUE TITLE
Revisit TestConfig class, which has too few public methods.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-python-devtools#10]
Issues:
1. Too few public methods, which makes me wonder does this class has to be a class? (https://www.youtube.com/watch?v=o9pEzgHorH0)
2. The usage of the ArgumentParser in it is weird. It essentially parses an empty array. Why?

**Comment by troydai** [comment]
https://www.youtube.com/watch?v=o9pEzgHorH0

**Comment by v-iam** [comment]
1. Good point. It probably doesn't need to be a class. `ReplayableTest` stores an instance of `TestConfig` as an attribute but we really only care about `TestConfig.args`. It can probably just be a function.
2. I agree it is weird. I use [ConfigArgParse](https://github.com/bw2/ConfigArgParse) just to get the config file and env var handling, which has exactly the order of precedence that we want (environment variables > config file values > defaults). But it's based on argparse, and specifying commandline parameters to tests is unorthodox at best (plus it's not clear that consumers of azure-devtools will have a consistent way of doing so), so I skip the argument parsing part of it entirely. Nevertheless, it seems to be the easiest off-the-shelf way to get the configuration mechanism we want.
