### ISSUE TITLE
Mapping to underlying VCR record modes is wrong

### ISSUE THREAD

**Issue by v-iam** [Azure/azure-python-devtools#21]
Currently `ReplayableTest.__init__` passes `self.config.record_mode` through unchanged as `record_mode` to `vcr.VCR()`. But it's a boolean value, which is not an appropriate value for that argument. It should be a string. Somehow it seems to work ok regardless? But I think it only does so incidentally.

To match what I believe we expect (and what I claim is done in #19), we should pass `record_mode` like this:
```python
record_mode='all' if self.config.record_mode else 'once'
```

**Comment by lmazuel** [comment]
Fixed
