### ISSUE TITLE
Releases will fail due to deprecated upload URL

### ISSUE THREAD

**Issue by v-iam** [Azure/azure-python-devtools#28]
This appears in the Jenkins output for the 0.5.0 release, which was [not successfully pushed to PyPI](https://travis-ci.org/Azure/azure-python-devtools/jobs/248508319):

```
Uploading distributions to https://pypi.python.org/pypi
Note: you are uploading to the old upload URL. It's recommended to use the new URL
"https://upload.pypi.org/legacy/" or to leave the URL unspecified and allow twine to choose.
Uploading azure_devtools-0.5.0-py2.py3-none-any.whl
HTTPError: 410 Client Error: Gone (This API has been deprecated and removed from legacy PyPI
in favor of using the APIs available in the new PyPI.org implementation of PyPI
(located at https://pypi.org/).
This is a 24h brownout of the API and access will be restored on June 30th. Please switch to PyPI.ORG
for uploads prior to July 3rd when this API will be removed for good. For more information about
migrating your use of this API to PyPI.org, please see
https://packaging.python.org/guides/migrating-to-pypi-org/#uploading.
For more information about the sunsetting of this API, please see
https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html)
for url: https://pypi.python.org/pypi
```

**Comment by v-iam** [comment]
@lmazuel I was looking for resources to point you to on this and found [this thread](https://github.com/travis-ci/dpl/issues/655). Then I looked at who was commenting on it. So I guess you are aware of it. :)

**Comment by lmazuel** [comment]
lol yes :)
I have to update PYPI_SERVER in Travis

**Comment by lmazuel** [comment]
Updated in Travis
![image](https://user-images.githubusercontent.com/1050156/27715443-02ba43c8-5cec-11e7-8753-3dd8e5cde0a2.png)

**Comment by lmazuel** [comment]
@troydai @v-iam 
Since I updated the Travis configuration, I restarted the job and it was enough to publish:
https://pypi.python.org/pypi/azure-devtools/0.5.0
