### ISSUE TITLE
Test preparer deletion order

### ISSUE THREAD

**Issue by dragonfly91** [Azure/azure-python-devtools#29]
I created 3 preparers: P1, P2 and P3. These depend on each other as such: P3 depends on P2 and P2 depends on P1. I've decorated the preparers on my test method in the order: P1, P2, P3. During resource creation, everything goes well. But during resource deletion, the order seems to be: P1, P2, P3 - whereas the order should be: P3, P2, P1. 

Please look into this!

**Comment by troydai** [comment]
https://github.com/Azure/azure-python-devtools/blob/master/src/azure_devtools/scenario_tests/preparers.py#L44

the sequence of the cleanup should be reversed (Russian doll model)

**Comment by tjprescott** [comment]
So @troydai is this a devtools bug?  Can we get this fixed. It really makes re-recording the backup module tests a pain.

**Comment by troydai** [comment]
Let's talk about this tomorrow. In short, we should fix this.

**Comment by dragonfly91** [comment]
Is this fixed? If not, when are you planning to fix this?

**Comment by tjprescott** [comment]
AFAIK this is still an issue. @troydai can you confirm?

**Comment by troydai** [comment]
@dragonfly91, unfortunately, it is not fixed yet. I'll take a look shortly.

**Comment by troydai** [comment]
Fixed in #44
