### ISSUE TITLE
Method "create_temp_file" with `full_random` causes recording failures

### ISSUE THREAD

**Issue by williexu** [Azure/azure-python-devtools#36]
https://github.com/Azure/azure-python-devtools/blob/b90f3211e7356c0c572bb972e619044a1a0c1493/src/azure_devtools/scenario_tests/base.py#L32
If create_temp_file is called and the `full_random` flag is set to True, the temp_file will have randomized bytes that may not be valid characters. Requests using that data that are being recorded will fail.

It would be nice to have randomized VALID characters instead.

**Comment by lmazuel** [comment]
Archiving repo, closing all issues.
