### ISSUE TITLE
VCR recording improvement

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-python-devtools#37]
1. Support serializing request/response payload with binary content. To reproduce, just try out the webapp [log download test](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py#L156)
2. For large payload, suggest throw during the recording instead of injecting `!!! The request body has been omitted from the recording because its...`.  You know, the test will still fail during the playback but becomes harder for me to figure out the cause since the test did pass during the recording

**Comment by yugangw-msft** [comment]
//cc: @tjprescott @troydai

**Comment by tjprescott** [comment]
It really is only applicable when you know you don't care about the contents of the large body. For every single case where there is a response body you care about that is larger than the threshold, this throws up a very frustrating roadblock as you have to use a workaround to change the size.

**Comment by lmazuel** [comment]
Archiving repo, closing all issues.
