### ISSUE TITLE
src/azure_devtools/ci_tools/github_tools.py uses Python3-only syntax

### ISSUE THREAD

**Issue by olasd** [Azure/azure-python-devtools#53]
Hi!

While updating the azure-python-devtools Debian package, I came across some Python3-only syntax in the ci_tools submodule (the keyword-only argument lone `*`).

I'll exclude that submodule from the Python2 Debian package, but I guess the packaging metadata should be updated, and/or the submodule excluded from setup.py on Python2.

Thanks!

**Comment by lmazuel** [comment]
Hi @olasd 
I'm sorry I'm just seeing your issue right now. This is a package which is entirely designed for testing and CI, I'm surprised you'd want to create a Debian package about it?
