### ISSUE TITLE
MSAL (AAD v2.0) requests are recorded

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-python-devtools#74]
`azure_devtools.scenario_tests.recording_processors.OAuthRequestResponsesFilter` doesn't recognize MSAL requests due to the URL change in [AAD v2.0](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow).

https://github.com/Azure/azure-python-devtools/blob/aae33c216028960fbf54e70dcb1c579600034054/src/azure_devtools/scenario_tests/recording_processors.py#L132-L141

This results in all https://login.microsoftonline.com requests being recorded, including

- Tenant discovery request: `GET https://login.microsoftonline.com/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/v2.0/.well-known/openid-configuration`
- Get access token request: `POST https://login.microsoftonline.com/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/oauth2/v2.0/token`

Actually, all requests to https://login.microsoftonline.com should be ignored as it is related to authentication which is patched in playback mode.

**Comment by lmazuel** [comment]
Archiving repo, closing all issues.
